default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  primary:
    <<: *default
    migrations_paths: db/migrate
    database: direct-white-label_development
  primary_replica:
    <<: *default
    migrations_paths: db/migrate
    database: direct-white-label_development_replica
    replica: true
  direct:
    migrations_paths: db/direct_migrate
    adapter: postgresql
    schema_search_path: ant
    url: <%= ENV["DIRECT_DATABASE_URL"] %>
  direct_replica:
    adapter: postgresql
    schema_search_path: ant
    url: <%= ENV["DIRECT_DATABASE_URL"] %>
    replica: true

test:
  <<: *default
  database: direct-white-label_test

production:
  primary:
    adapter: postgresql
    database: direct-white-label_production
  primary_replica:
    adapter: postgresql
    database: direct-white-label_production_replica
  direct:
    migrations_paths: db/direct_migrate
    adapter: postgresql
    schema_search_path:  ant
    url: <%= ENV["DIRECT_DATABASE_URL"] %>
  direct_replica:
    adapter: postgresql
    schema_search_path:  ant
    url: <%= ENV["DIRECT_DATABASE_URL"] %>
    replica: true
